import { useState, useRef } from 'react'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import logo from '@/assets/logo.svg'

export type AppSource = {
    jsUrl: string
    wasmUrl?: string
    canvasSelector: string
}

type CardId = 'demo' | 'custom'

interface Props {
    onLoad: (source: AppSource) => void
    loading?: boolean
    error?: string
}

export function Launcher({ onLoad, loading = false, error }: Props) {
    const [selected, setSelected] = useState<CardId>('demo')
    const [jsFile, setJsFile] = useState<File | null>(null)
    const [wasmFile, setWasmFile] = useState<File | null>(null)
    const [canvasSelector, setCanvasSelector] = useState('')
    const jsInputRef = useRef<HTMLInputElement>(null)
    const wasmInputRef = useRef<HTMLInputElement>(null)

    function handleLoad() {
        if (selected === 'demo') {
            onLoad({ jsUrl: '/wasm/demo.js', canvasSelector: '#bevy-canvas' })
        } else {
            if (!jsFile || !wasmFile) return
            onLoad({
                jsUrl: URL.createObjectURL(jsFile),
                wasmUrl: URL.createObjectURL(wasmFile),
                canvasSelector,
            })
        }
    }

    const canLoad = !loading && (selected === 'demo' || (jsFile !== null && wasmFile !== null))

    return (
        <div className="h-full overflow-y-auto">
            <div className="flex flex-col items-center justify-center min-h-full gap-6 p-8">
                <header className="flex items-center gap-4">
                    <img src={logo} alt="Bevy Remote Playground logo" className="w-16 h-16 shrink-0" />
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight">Bevy Remote Playground</h1>
                        <p className="text-muted-foreground text-sm mt-1">Select which WASM app to load.</p>
                    </div>
                </header>

                <div className="flex flex-col gap-3 w-80">
                    {/* Demo card */}
                    <Card
                        role="button"
                        tabIndex={0}
                        onClick={() => setSelected('demo')}
                        onKeyDown={(e) => e.key === 'Enter' && setSelected('demo')}
                        className={cn(
                            'cursor-pointer transition-colors',
                            selected === 'demo'
                                ? 'border-primary ring-1 ring-primary'
                                : 'hover:border-muted-foreground/50'
                        )}
                    >
                        <CardHeader>
                            <CardTitle>Demo</CardTitle>
                            <CardDescription>Bevy's built-in 3D cube example, with a custom BRP method.</CardDescription>
                        </CardHeader>
                    </Card>

                    {/* Custom card */}
                    <Card
                        role="button"
                        tabIndex={0}
                        onClick={() => setSelected('custom')}
                        onKeyDown={(e) => e.key === 'Enter' && setSelected('custom')}
                        className={cn(
                            'cursor-pointer transition-colors',
                            selected === 'custom'
                                ? 'border-primary ring-1 ring-primary'
                                : 'hover:border-muted-foreground/50'
                        )}
                    >
                        <CardHeader>
                            <CardTitle>Custom</CardTitle>
                            <CardDescription>Load your own WASM-enabled Bevy app.</CardDescription>
                        </CardHeader>
                        {selected === 'custom' && (
                            <CardContent className="flex flex-col gap-3">
                                <div className="text-sm text-muted-foreground">
                                    <p className="font-medium text-foreground mb-1">Requirements</p>
                                    <ul className="list-disc list-inside space-y-0.5">
                                        <li>A Bevy app with the <code className="text-xs bg-muted px-1 py-0.5 rounded">RemoteWasmPlugin</code> added.</li>
                                        <li>JavaScript and WASM files generated by <code className="text-xs bg-muted px-1 py-0.5 rounded">wasm-bindgen</code>.</li>
                                    </ul>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <Label>JS glue file</Label>
                                    <input
                                        ref={jsInputRef}
                                        type="file"
                                        accept=".js"
                                        className="hidden"
                                        onChange={(e) => setJsFile(e.target.files?.[0] ?? null)}
                                    />
                                    <Button variant="outline" type="button" onClick={(e) => { e.stopPropagation(); jsInputRef.current?.click() }}>
                                        {jsFile ? jsFile.name : 'Choose .js'}
                                    </Button>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <Label>WASM file (often <code className="text-xs bg-muted px-1 py-0.5 rounded">*_bg.wasm</code>)</Label>
                                    <input
                                        ref={wasmInputRef}
                                        type="file"
                                        accept=".wasm"
                                        className="hidden"
                                        onChange={(e) => setWasmFile(e.target.files?.[0] ?? null)}
                                    />
                                    <Button variant="outline" type="button" onClick={(e) => { e.stopPropagation(); wasmInputRef.current?.click() }}>
                                        {wasmFile ? wasmFile.name : 'Choose .wasm'}
                                    </Button>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <Label>Canvas selector <span className="text-muted-foreground font-normal">(optional)</span></Label>
                                    <input
                                        type="text"
                                        value={canvasSelector}
                                        onClick={(e) => e.stopPropagation()}
                                        onChange={(e) => setCanvasSelector(e.target.value)}
                                        placeholder="e.g. #bevy-canvas"
                                        className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-xs transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                                    />
                                </div>
                            </CardContent>
                        )}
                    </Card>
                </div>

                <Button className="w-80" onClick={handleLoad} disabled={!canLoad}>
                    {loading ? 'Loading…' : 'Load'}
                </Button>
                {error && (
                    <p className="w-80 text-sm text-destructive bg-destructive/10 border border-destructive/30 rounded-md px-3 py-2">
                        {error}
                    </p>
                )}
            </div>
        </div>
    )
}
