/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const getBridge: () => any;
export const wasm_bindgen__closure__destroy__h9892534543824ac9: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h04fb56d82a4a849e: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h2d167d9aca9461dd: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h939e6ebdfbac2c24: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__ha9ab3622078cf647: (a: number, b: number, c: number, d: number) => any;
export const wasm_bindgen__convert__closures_____invoke__he8b7669b1c2f4f7f: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5ef4b39df39c750f: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hc16c84bab4b73e32: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04dc33acbb81e223_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h737e02440c8e50ed: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h87e4beefe34d563a: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb545dbcfbfd18dcf: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb02c922985c0b455: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
