/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const getBridge: () => any;
export const wasm_bindgen__convert__closures_____invoke__h7f5743b555e902e0: (a: number, b: number, c: number, d: number) => any;
export const wasm_bindgen__convert__closures_____invoke__hfc650d981c77f0de: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hc6603a469a472c93: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__haf4338cfb784bc20: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h221a5ce2a7b7713a_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha0b1751c3f4b0ca6: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h78aaa04061365893: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hf14f5514eab97422: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb3652a905020859b: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
